language: node_js
node_js:
  - 10.15.3
install:
  - npm install
before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
script:
  - node_modules/.bin/newman run hello_postman_auto_collection.json
  - npm run cypress:run
