matrix:
  include:
    - language: python
      python:
        - 3.4
      install:
        - pip install -r requirements.txt
      before_script:
        - python --version
      script:
        - python export_postman_collection.py

    - language: node_js
      node_js:
        - 10.15.3
      install:
        - npm install
      before_script:
        - node --version
        - npm --version
        - node_modules/.bin/newman --version
      script:
        - node_modules/.bin/newman run hello_postman_collection.json
        - npm run cypress:run
