language: python
python: 3.6
install:
- pip install -r requirements.txt
script: python -m unittest
deploy:
  provider: heroku
  api_key:
    secure: Uw1LAVC4orp5JXTVwaa7LetnZ20XI79MHY3vaikx/yFap2iM57cbd7MFqvDcLCOMWG2kPo+xXnl0hiNGCXNtqT3jQ9SJ9Z4uRPrYkNNEzBcUorlYYNTjEZZrfRKZEsqioWxM9aawH6Em2EVmF8Y03f8QbKKdrZ6BTJsbwVrrbIcwNCvUsjJ7s9ps7Bcuf9x0x+EWa1OqD+ZqhX1dX7t/55Onf+f/958pCfQs9fANfcsaDER3mtg0hcJT//pnyI1POk57h0CBzG8ABZk99syfuK546FPy07MWuLAox7k2cjkFW2LgiIQAELHUZYFXBZ057R4510SiORzA0zLS0VFOLOLCiKIhb/DJYKfs8vxZEDaTeRQysmFjYkUdNiGZkiZAt+ms5MxChQDlEsiIYEmHWT2XF+9YBN7WT2XiC0SiziCxPjBVFcy4uSVAhsfYvJ9u5aEnBG2wKKAsm8klHauH32L4Lq+nMy+cr0tw3lIsPAJwkJoRo2196WtAUZSFbJ1mRv5gvu1zZsmymg9AD3DVkCtY0EszPH1T0r1DewdDrCQJ4idp2qdiB6hgrw9xLGpqt+a5sCe21yqvnljsDAJ2kp0sivjuHUAAwee5ijiIT8r+gpKjxDb4q//cz1M+hiZM2CBsqKT88DGTPjDrfM2FDi86svdpJTjgoQtQsQJk0k0=
  app: postcards-backend
